name: Local CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies and run tests (Frontend)
        run: |
          cd frontend
          npm install
          npm run test

      - name: Install dependencies and run tests (Backend)
        run: |
          cd backend
          npm install
          npm run test

      - name: Build Docker images
        run: |
          docker build -t recipe-frontend:latest ./frontend
          docker build -t recipe-backend:latest ./backend

      - name: Run Docker Compose
        run: |
          docker-compose up --build -d